// Extracts only the vector lettering from the brand SVG; the embedded raster clapper is rebuilt in 3D.
import { readFile, writeFile, mkdir } from 'node:fs/promises';

const source = new URL('../Logo Transparent.svg', import.meta.url);
const target = new URL('../src/intro/logo-data.ts', import.meta.url);
const svg = await readFile(source, 'utf8');

const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1].split(/\s+/).map(Number);
if (!viewBox || viewBox.length !== 4) throw new Error('Logo SVG has no viewBox.');

const groupIds = ['Zoom_In_Text', 'Zoom_In_Text-2', 'Film_Fest_Text', 'Film_Fest_Text-2', 'Movie_Icon'];
const starts = groupIds
  .map((id) => ({ id, index: svg.indexOf(`<g id="${id}"`) }))
  .sort((a, b) => a.index - b.index);
if (starts.some((entry) => entry.index < 0)) throw new Error('Logo SVG is missing an expected group.');

const markup = {};
starts.forEach((entry, i) => {
  const end = i + 1 < starts.length ? starts[i + 1].index : svg.length;
  const block = svg.slice(entry.index, end);
  markup[entry.id] = [...block.matchAll(/<(polygon|path|rect)\b[^>]*\/>/g)].map((match) =>
    match[0].replace(/\sclass="[^"]*"/, '')
  );
});

const icon = svg.match(/<image width="([\d.]+)" height="([\d.]+)" transform="translate\(([-\d.]+) ([-\d.]+)\)"/);
if (!icon) throw new Error('Logo SVG has no Movie Icon image.');

const body = `// Generated by scripts/extract-logo.mjs from "Logo Transparent.svg". Do not edit.
export const LOGO_SIZE = { width: ${viewBox[2]}, height: ${viewBox[3]} } as const;
export const ICON_BOX = { x: ${icon[3]}, y: ${icon[4]}, width: ${icon[1]}, height: ${icon[2]} } as const;
export const LOGO_LAYERS = {
  zoomShadow: ${JSON.stringify(markup['Zoom_In_Text'], null, 2)},
  zoomFront: ${JSON.stringify(markup['Zoom_In_Text-2'], null, 2)},
  filmShadow: ${JSON.stringify(markup['Film_Fest_Text'], null, 2)},
  filmFront: ${JSON.stringify(markup['Film_Fest_Text-2'], null, 2)}
} as const;
`;

await mkdir(new URL('../src/intro/', import.meta.url), { recursive: true });
await writeFile(target, body);
console.log(
  Object.entries(markup).map(([id, items]) => `${id}: ${items.length}`).join(', '),
  `-> ${(body.length / 1024).toFixed(1)} KB`
);
